-- The Bold Italic — crosswords table + RLS + seed (run in Supabase SQL editor)
create table if not exists public.crosswords (
  id bigint generated always as identity primary key,
  slug text unique not null,
  title text not null,
  subtitle text,
  number int,
  puzzle_date date,
  size int not null,
  symmetry boolean default true,
  grid jsonb not null,
  clues jsonb not null,
  published boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.crosswords enable row level security;
drop policy if exists crosswords_read_published on public.crosswords;
create policy crosswords_read_published on public.crosswords for select using (published = true);
drop policy if exists crosswords_admin_all on public.crosswords;
create policy crosswords_admin_all on public.crosswords for all to authenticated using (true) with check (true);

insert into public.crosswords (slug,title,subtitle,number,puzzle_date,size,symmetry,grid,clues,published) values
('hump-day-2','Hump Day Crossword','San Francisco Edition',2,'2026-07-01',9,true,'["GAMER#FOR","ALIVE#LIE","PENINSULA","###DOCKED","CAVE#REDS","ALONSO###","COITTOWER","HUD#AGILE","EDS#BEGIN"]'::jsonb,'{"1A":"A GDC attendee, or someone glued to an arcade in the Metreon","6A":"In favor of, as a raucous vote at the Board of Supervisors","9A":"How the Castro feels on the last Sunday in June","10A":"\"The city''s flat,\" for one (try biking up Filbert Street)","11A":"The tech-thick strip running south toward San Jose, with the city at its tip","13A":"Tied up at the Embarcadero, as the Larkspur ferry","14A":"Give in, or what the waves carved into the cliffs below the Sutro Baths","17A":"Sips from a Napa tasting flight, casually","18A":"Alicia ___, the Cuban ballet legend long honored by SF Ballet","20A":"Telegraph Hill spire funded by Lillie Hitchcock Coit''s bequest","24A":"Fed. dept. behind much of the city''s affordable-housing money","25A":"Nimble, or the sprint-based method ruling SoMa''s software shops","26A":"Newsroom chiefs at the Chronicle, for short","27A":"Start, as the Bay to Breakers gun downtown","1D":"Clothing giant founded on Ocean Avenue in 1969","2D":"Anchor Steam, for one","3D":"Tiny stretch of time, on a Muni arrival sign: Abbr.","4D":"Plain to see, like the fog pouring over Twin Peaks","5D":"\"Biggest Little City,\" a quick hop east over the Sierra","6D":"Whale''s tail, glimpsed on a Farallones boat trip","7D":"Well-___ (smooth-running, like a restored cable car''s gears)","8D":"Peruses, as the zines at City Lights","12D":"Miser at A.C.T.''s annual \"A Christmas Carol\"","14D":"Hidden hoard, or a stash spot on a Lands End geocaching hunt","15D":"How a poet delivers at a Mission open mic","16D":"Cancels, as a parking ticket you contest at City Hall","19D":"Take a ___ at it, like a first-timer on the Dolores Park slackline","21D":"A drag queen''s crowning glory at Oasis","22D":"Yale grad who decamped to SF for a startup","23D":"Kylo ___ (Lucasfilm is just across the bridge)"}'::jsonb,true),
('hump-day-1','Hump Day Crossword','San Francisco Edition',1,'2026-06-24',9,true,'["PATHS#ART","ISAAC#ROE","CHINATOWN","###DRAMAS","ABEL#BANE","SOLEIL###","SOURDOUGH","END#LINER","SEE#EDITS"]'::jsonb,'{"1A":"Crosstown Trail segments that lace the city hill to shore","6A":"What fills the de Young and the Legion of Honor","9A":"Sci-fi''s Asimov, born an ocean away but shelved in every SF bookstore","10A":"Ikura, at a Japantown sushi counter","11A":"North America''s oldest, entered through the Dragon Gate on Grant","13A":"What A.C.T. and the Magic Theatre stage","14A":"Norwegian math whiz with a prize in his name (not the Cain kind)","17A":"Ruin, or Batman''s back-breaking foe","18A":"Cirque du ___, whose big top pitches near the bay","20A":"Boudin''s been pulling it from wharf ovens since 1849","24A":"Lands ___, where the Sutro Baths met the sea","25A":"Cunard crosser, or the liner notes in a vinyl sleeve","26A":"Take in, as the view from Twin Peaks","27A":"Blue-pencil fixes from a Chronicle desk","1D":"Camera-roll keeper, casually","2D":"Forehead smudge on Ash Wednesday at the Mission''s old basilica","3D":"___ chi, the dawn ritual in Portsmouth Square","4D":"Comic Chelsea, or a celebrity''s on-tour minder","5D":"Mark left after the ''06 quake, maybe","6D":"What pulls you into a Mission roastery","7D":"Atkinson of \"Mr. Bean,\" or Marin''s Mount ___","8D":"Keyed up, like a Giants crowd in the ninth","12D":"Format the Examiner once printed in","14D":"Mule trains, or stubborn sorts","15D":"Trailblazing Daniel, or crooner Pat","16D":"Give the slip to, as fog dodging the East Bay","19D":"Sitting unused, like a cable car on the turntable overnight","21D":"Spiky-shelled treat on an omakase menu","22D":"Wrangle, as a permit from City Hall","23D":"Shift lengths at a SoMa startup: Abbr."}'::jsonb,true),
('the-mini-1','The Mini','San Francisco Edition',1,'2026-06-17',5,true,'["MAD##","ACRES","PRIDE","SEVEN","##END"]'::jsonb,'{"1A":"Steaming, like a rider who just watched the J Church pull away","4A":"Golden Gate Park sprawls across more than 1,000 of them","7A":"Late-June celebration that floods Market Street with rainbow flags","8A":"Roughly the Richter reading of the 1989 Loma Prieta quake","9A":"Lands ___, the cliffside lookout above the ruined Sutro Baths","1D":"Phone apps for surviving the city''s maze of one-way streets","2D":"Football-field-ish unit of land","3D":"JFK ___, the Golden Gate Park road that''s now mostly car-free","5D":"Garden paradise of Genesis","6D":"Fire off, as a text"}'::jsonb,true)
on conflict (slug) do update set title=excluded.title, subtitle=excluded.subtitle, number=excluded.number, puzzle_date=excluded.puzzle_date, size=excluded.size, symmetry=excluded.symmetry, grid=excluded.grid, clues=excluded.clues, published=excluded.published, updated_at=now();
